openapi: 3.0.3
info:
  title: Finarkein API
  version: 1.0.0
  description: |
    # Finarkein API Documentation

    ## Authentication

    This API uses OAuth 2.0 Client Credentials flow for authentication.

    ### Getting Your Credentials

    Each workspace has unique credentials:
    - **Client ID**: Your workspace-specific client identifier
    - **Client Secret**: Your workspace-specific secret key
    - **Workspace ID**: Your workspace identifier (e.g., "tsfsl", "demo")

    ### How to Authenticate

    1. Click the "Authorize" button above
    2. Select your workspace authentication profile
    3. Zudoku will automatically handle authentication
    4. All API requests will include proper credentials

    ### Workspace Parameters

    Most endpoints require `workspace` and `flowId` path parameters. **These are automatically populated from your workspace credentials stored on the backend.**

    When you make an API request:
    1. The proxy fetches your workspace credentials from the backend
    2. Path parameters like `{workspace}` and `{flowId}` are automatically replaced with your actual values
    3. You don't need to manually enter these values - they're handled for you!

    The workspace value is determined by:
    - Your authenticated user's workspace metadata (if logged in via Clerk)
    - Or the default workspace configured in the backend environment
  contact: {}
servers:
- url: http://localhost:3001/api
  description: Finarkein API (via secure proxy)
paths:
  /{workspace}/dp/nerv/{flowId}:
    post:
      tags:
      - Nerv
      summary: New Run
      description: New Run
      operationId: newRun
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                consentTemplateId:
                  type: string
                  example: f2f86ccb-60fe-4ec4-b58d-3f90a4559938
                customerMobileNumber:
                  type: string
                  example: '9881908250'
                redirectUrl:
                  type: string
                  example: https://dev.fnrk.in/o/{{workspace}}/thank-you
                webhook:
                  type: object
                  properties:
                    addOnParams:
                      type: object
                      properties:
                        application:
                          type: string
                          example: APP091234
                        customerSegment:
                          type: string
                          example: hni
                        other-key-1:
                          type: string
                          example: other-value-1
                    consentStatus:
                      type: string
                      example: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
                    dataPush:
                      type: string
                      example: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
                    flowRunStatus:
                      type: string
                      example: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
            examples:
              New Run:
                value:
                  consentTemplateId: f2f86ccb-60fe-4ec4-b58d-3f90a4559938
                  customerMobileNumber: '9881908250'
                  redirectUrl: https://dev.fnrk.in/o/{{workspace}}/thank-you
                  webhook:
                    addOnParams:
                      application: APP091234
                      customerSegment: hni
                      other-key-1: other-value-1
                    consentStatus: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
                    dataPush: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
                    flowRunStatus: https://webhook.site/e497c184-6f87-44b9-bfb0-a8767b17b920
      responses:
        '200':
          description: New Run
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectUrl:
                    type: string
                    example: https://dev.fnrk.in/v2/bf75efbb-5604-42d8-8163-f29cc7a0f5c6
                  requestId:
                    type: string
                    example: bf75efbb-5604-42d8-8163-f29cc7a0f5c6
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        default: acme
        example: acme
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
    - name: flowId
      in: path
      required: true
      description: The Nerv flow identifier - **automatically populated from backend credentials**
      schema:
        type: string
        default: 376b71fe-009b-4154-850c-fa0eb65b4d5a
        example: 376b71fe-009b-4154-850c-fa0eb65b4d5a
      x-example-note: This value is automatically replaced by the proxy with your actual flow ID
  /{workspace}/dp/nerv/fetch/{flowId}:
    post:
      tags:
      - Nerv
      summary: New Recurring Run
      security:
      - bearerAuth: []
      description: New recurring data fetch run
      operationId: newRecurringRun
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                consentHandle:
                  type: string
                  example: bf75efbb-5604-42d8-8163-f29cc7a0f5c6
                webhook:
                  type: object
                  properties:
                    addOnParams:
                      type: object
                    dataPush:
                      type: string
                    flowRunStatus:
                      type: string
      responses:
        '200':
          description: New Recurring Run
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: tsfsl
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
    - name: flowId
      in: path
      required: true
      description: The Nerv flow identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: 376b71fe-009b-4154-850c-fa0eb65b4d5a
      x-example-note: This value is automatically replaced by the proxy with your actual flow ID
  /{workspace}/dp/nerv/{flowId}/{requestId}/status:
    get:
      tags:
      - Nerv
      summary: Get Status
      description: Get Status
      operationId: getStatus
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Get Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  state:
                    type: object
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: tsfsl
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
    - name: flowId
      in: path
      required: true
      description: The Nerv flow identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: 376b71fe-009b-4154-850c-fa0eb65b4d5a
      x-example-note: This value is automatically replaced by the proxy with your actual flow ID
    - name: requestId
      in: path
      required: true
      schema:
        type: string
  /{workspace}/dp/nerv/{flowId}/{requestId}/result:
    get:
      tags:
      - Nerv
      summary: Get Result
      description: Get Result
      operationId: getResult
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Get Result
          content:
            application/json:
              schema:
                type: object
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: tsfsl
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
    - name: flowId
      in: path
      required: true
      description: The Nerv flow identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: 376b71fe-009b-4154-850c-fa0eb65b4d5a
      x-example-note: This value is automatically replaced by the proxy with your actual flow ID
    - name: requestId
      in: path
      required: true
      schema:
        type: string
  /{workspace}/consent/aa/template:
    get:
      tags:
      - Consent templates
      summary: Browse consent templates
      description: Browse consent templates
      operationId: browseConsentTemplates
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Success
    post:
      tags:
      - Consent templates
      summary: Create new Consent Template
      security:
      - bearerAuth: []
      description: Create a new consent template
      operationId: createNewConsentTemplate
      responses:
        '200':
          description: Success
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: tsfsl
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
  /{workspace}/consent/aa/template/{id}:
    get:
      tags:
      - Consent templates
      summary: Get consent template by identifier
      description: Get consent template by identifier
      operationId: getConsentTemplateByIdentifier
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Success
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: Identifier for the template
  /{workspace}/institutions/aa/fip:
    get:
      tags:
      - Institutions
      summary: Get FIPs on AA network
      description: Get FIPs on AA network
      operationId: getFipsOnAaNetwork
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
    patch:
      tags:
      - Institutions
      summary: Update (enable/disable) FIP(s) status
      description: Update (enable/disable) FIP(s) status
      operationId: updateEnableDisableFipSStatus
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fips:
                  type: array
                  items:
                    type: object
      responses:
        '202':
          description: Success
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
        example: tsfsl
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
  /{workspace}/institutions/aa/fip/status:
    get:
      tags:
      - Institutions
      summary: Get FIP Health Status
      description: Get FIP Health Status
      operationId: getFipHealthStatus
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Success
    parameters:
    - name: workspace
      in: path
      required: true
      description: Your workspace identifier - **automatically populated from backend credentials**
      schema:
        type: string
      x-example-note: This value is automatically replaced by the proxy with your actual workspace ID
  /token:
    post:
      tags:
      - Authentication
      summary: Generate Access Token
      description: |
        # Generate OAuth 2.0 Access Token
        
        ## Overview
        This endpoint generates an OAuth 2.0 access token using the **Client Credentials Grant** flow.
        
        ## Authentication
        **IMPORTANT:** This endpoint uses automatic authentication through the proxy.
        Simply authorize with your workspace profile and the proxy will handle credential exchange.
        
        ## Request Body
        Must include `grant_type=client_credentials` as form data.
      operationId: generateAccessToken
      parameters: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
              properties:
                grant_type:
                  type: string
                  default: client_credentials
                  enum:
                    - client_credentials
                  description: Must be set to 'client_credentials'
      responses:
        '200':
          description: Generate Access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: number
                  token_type:
                    type: string
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication handled automatically by the proxy
tags:
- name: Authentication
  description: Endpoints for obtaining access tokens
- name: Nerv
- name: Consent templates
- name: Institutions
